
/**************************************************************
 *	
 *	harvest, 8 bit, 11025Hz,
 *	1 channel, 7987 bytes/channel
 *	Total Size: 1 * 7987 + 4 (header) = 8031 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anna\Desktop\FinalProject_AnnaStenstrom\harvest.wav
 *	Time-stamp: Tue Nov 04 19:54:26 2014
 *	
 **************************************************************/

#ifndef __HARVESTH__
#define __HARVESTH__

#define HARVESTFREQ 11025
#define HARVESTLEN 7987

extern const unsigned char harvest[7987];

#endif /* __HARVESTH__ */
