
/**************************************************************
 *	
 *	HarvestMoon, 8 bit, 11025Hz,
 *	1 channel, 1129248 bytes/channel
 *	Total Size: 1 * 1129248 + 4 (header) = 1129292 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anna\Desktop\FinalProject_AnnaStenstrom\HarvestMoon.wav
 *	Time-stamp: Tue Nov 04 14:00:24 2014
 *	
 **************************************************************/

#ifndef __HARVESTMOONH__
#define __HARVESTMOONH__

#define HARVESTMOONFREQ 11025
#define HARVESTMOONLEN 1129248

extern const unsigned char HarvestMoon[1129248];

#endif /* __HARVESTMOONH__ */
