
/**************************************************************
 *	
 *	secret, 8 bit, 11025Hz,
 *	1 channel, 20963 bytes/channel
 *	Total Size: 1 * 20963 + 4 (header) = 21007 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anna\Desktop\AnnaStenstrom_P06\secret.wav
 *	Time-stamp: Sun Nov 30 21:35:42 2014
 *	
 **************************************************************/

#ifndef __SECRETH__
#define __SECRETH__

#define SECRETFREQ 11025
#define SECRETLEN 20963

extern const unsigned char secret[20963];

#endif /* __SECRETH__ */
